const fs = require('fs');
const path = require('path');

// Helper to format date as yyyy-MM-dd
const formatDate = (date) => {
  const yyyy = date.getFullYear();
  const mm = String(date.getMonth() + 1).padStart(2, '0');
  const dd = String(date.getDate()).padStart(2, '0');
  return `${yyyy}-${mm}-${dd}`;
};

const generateId = () => {
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
    const r = Math.random() * 16 | 0, v = c === 'x' ? r : (r & 0x3 | 0x8);
    return v.toString(16);
  });
};

const seedData = () => {
  const fakeUsers = [
    { id: generateId(), name: 'Alex', color: '#10B981', avatar: null, pin: null },
    { id: generateId(), name: 'Jordan', color: '#8B5CF6', avatar: null, pin: null },
    { id: generateId(), name: 'Sam', color: '#F43F5E', avatar: null, pin: null },
  ];

  const fakeHabits = [
    { title: 'Drink Water', frequency: 'daily', color: '#3B82F6', icon: 'droplet', category_id: 'cat-1' },
    { title: 'Morning Run', frequency: 'daily', color: '#F97316', icon: 'zap', category_id: 'cat-2' },
    { title: 'Read 20 Pages', frequency: 'daily', color: '#8B5CF6', icon: 'book', category_id: 'cat-3' },
    { title: 'Meditate', frequency: 'daily', color: '#10B981', icon: 'wind', category_id: 'cat-4' },
    { title: 'Journal', frequency: 'daily', color: '#EAB308', icon: 'pen-tool', category_id: 'cat-5' },
  ];

  const profiles = [];
  const habits = [];
  const completions = [];

  const today = new Date();

  for (const user of fakeUsers) {
    profiles.push({
      ...user,
      created_at: new Date().toISOString()
    });

    for (const h of fakeHabits) {
      const habitId = generateId();
      habits.push({
        id: habitId,
        profile_id: user.id,
        category_id: h.category_id,
        title: h.title,
        description: 'Generated by seeder',
        frequency: h.frequency,
        color: h.color,
        icon: h.icon,
        is_archived: 0,
        created_at: new Date().toISOString()
      });

      // Gen past 100 days
      for (let i = 0; i < 100; i++) {
        if (Math.random() < 0.8) { // 80% chance
          const pastDate = new Date();
          pastDate.setDate(today.getDate() - i);
          
          completions.push({
            id: generateId(),
            habit_id: habitId,
            date: formatDate(pastDate),
            completed_at: pastDate.toISOString(),
            note: null
          });
        }
      }
    }
  }

  const output = {
    profiles,
    habits,
    completions
  };

  const outputPath = path.resolve(__dirname, '../src/database/mockData.json');
  fs.writeFileSync(outputPath, JSON.stringify(output, null, 2), 'utf-8');
  console.log(`✅ Successfully generated seed data with ${profiles.length} profiles, ${habits.length} habits, and ${completions.length} completions!`);
  console.log(`📂 Saved to: src/database/mockData.json`);
};

seedData();
